version: 2

project_name: crtui

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE

nfpms:
  - id: default
    formats:
      - deb
      - rpm
      - apk
    vendor: crtui
    homepage: https://github.com/ksckaan1/crtui
    maintainer: Kaan Kuscu
    description: Terminal-based container registry management tool
    license: MIT

brews:
  - name: crtui
    repository:
      owner: ksckaan1
      name: homebrew-tap

aurs:
  - name: crtui-bin
    ids:
      - default
    git_url: "ssh://aur@aur.archlinux.org/crtui-bin.git"
    private_key: "{{ .Env.AUR_SSH_KEY }}"
    license: "MIT"
    description: "Terminal-based container registry management tool"
    homepage: "https://kaanksc.com"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: ksckaan1
    name: crtui
  draft: false
  prerelease: auto
  after_deploy:
    - script: bash
      name: upload_to_cloudsmith
      timeout: 2m
      cmd: bash scripts/upload_cloudsmith.sh

builds:
  - id: crtui
    main: ./cmd/crtui
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: crtui
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/ksckaan1/crtui/version.Version={{.Version}}
