name: Upload Packages

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x" # En güncel kararlı Python sürümünü kullanır

      - name: Install Cloudsmith CLI
        run: |
          python -m pip install --upgrade pip
          pip install --quiet cloudsmith-cli

      - name: Make Script Executable
        run: chmod +x scripts/upload_cloudsmith.sh

      - name: Run Cloudsmith Upload Script
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
        run: ./scripts/upload_cloudsmith.sh
